# Generated by Django 5.2.8 on 2025-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('target', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
